changes to readme for local setup
civictechindex/CTI-website-backend pull request #42
Opened 2021-03-25 04:53 UTC by kliu28

2021-03-26 01:45 UTC, cnk commented
@kliu28 Could you please move the "install Postgres" item down into the "no containers" section? If you are running docker, the database will be a container managed with docker-compose rather than being on your machine.

2021-03-26 01:46 UTC, cnk requested changes

2021-03-26 01:46 UTC, cnk commented on README.md
> +3. Install [PostgreSQL](https://www.postgresql.org/) if you haven't already.
This should be in the No Containers section. If using Docker, you do not need to install Postgres yourself.

2021-03-28 03:33 UTC, kliu28 commented
updated. also edited numbering just for editing's sake; markdown technically doesn't care about the actual numbers in a numbered list

2021-03-28 18:02 UTC, cnk approved these changes
Thanks for these updates!

2021-03-28 18:02 UTC, merged